// Generated by gencpp from file iri_adc_msgs/adc_juryAction.msg
// DO NOT EDIT!


#ifndef IRI_ADC_MSGS_MESSAGE_ADC_JURYACTION_H
#define IRI_ADC_MSGS_MESSAGE_ADC_JURYACTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <iri_adc_msgs/adc_juryActionGoal.h>
#include <iri_adc_msgs/adc_juryActionResult.h>
#include <iri_adc_msgs/adc_juryActionFeedback.h>

namespace iri_adc_msgs
{
template <class ContainerAllocator>
struct adc_juryAction_
{
  typedef adc_juryAction_<ContainerAllocator> Type;

  adc_juryAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  adc_juryAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::iri_adc_msgs::adc_juryActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::iri_adc_msgs::adc_juryActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::iri_adc_msgs::adc_juryActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::iri_adc_msgs::adc_juryAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iri_adc_msgs::adc_juryAction_<ContainerAllocator> const> ConstPtr;

}; // struct adc_juryAction_

typedef ::iri_adc_msgs::adc_juryAction_<std::allocator<void> > adc_juryAction;

typedef boost::shared_ptr< ::iri_adc_msgs::adc_juryAction > adc_juryActionPtr;
typedef boost::shared_ptr< ::iri_adc_msgs::adc_juryAction const> adc_juryActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iri_adc_msgs::adc_juryAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iri_adc_msgs::adc_juryAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iri_adc_msgs::adc_juryAction_<ContainerAllocator1> & lhs, const ::iri_adc_msgs::adc_juryAction_<ContainerAllocator2> & rhs)
{
  return lhs.action_goal == rhs.action_goal &&
    lhs.action_result == rhs.action_result &&
    lhs.action_feedback == rhs.action_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iri_adc_msgs::adc_juryAction_<ContainerAllocator1> & lhs, const ::iri_adc_msgs::adc_juryAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iri_adc_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::iri_adc_msgs::adc_juryAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iri_adc_msgs::adc_juryAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iri_adc_msgs::adc_juryAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iri_adc_msgs::adc_juryAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iri_adc_msgs::adc_juryAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iri_adc_msgs::adc_juryAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iri_adc_msgs::adc_juryAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baa6a3def05309cc9806c06ef70e5676";
  }

  static const char* value(const ::iri_adc_msgs::adc_juryAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbaa6a3def05309ccULL;
  static const uint64_t static_value2 = 0x9806c06ef70e5676ULL;
};

template<class ContainerAllocator>
struct DataType< ::iri_adc_msgs::adc_juryAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iri_adc_msgs/adc_juryAction";
  }

  static const char* value(const ::iri_adc_msgs::adc_juryAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iri_adc_msgs::adc_juryAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"adc_juryActionGoal action_goal\n"
"adc_juryActionResult action_result\n"
"adc_juryActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: iri_adc_msgs/adc_juryActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"adc_juryGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: iri_adc_msgs/adc_juryGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"###action\n"
"#goals\n"
"adc_goal_array goals\n"
"\n"
"================================================================================\n"
"MSG: iri_adc_msgs/adc_goal_array\n"
"Header     header\n"
"adc_goal[] goals\n"
"\n"
"================================================================================\n"
"MSG: iri_adc_msgs/adc_goal\n"
"#type definitions\n"
"uint8 PASSTHROUGH_GOAL=0\n"
"uint8 STOP_GOAL=1\n"
"uint8 PARKING_GOAL=2\n"
"\n"
"string id       # goal identifier\n"
"float32 x       # x coordinates in meters [m]\n"
"float32 y       # y coordinate in meters [m]\n"
"float32 yaw     # yaw orientation in radians [rad]\n"
"int32 type      # see type definitions above\n"
"\n"
"================================================================================\n"
"MSG: iri_adc_msgs/adc_juryActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"adc_juryResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: iri_adc_msgs/adc_juryResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result\n"
"\n"
"================================================================================\n"
"MSG: iri_adc_msgs/adc_juryActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"adc_juryFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: iri_adc_msgs/adc_juryFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"\n"
"#constant string for feedback status\n"
"string NAVIGATING         = Navigating to goal\n"
"string STOPPED            = Stopped at goal\n"
"string PARKING            = Parking at goal\n"
"string PARKED             = Parked at goal\n"
"string UNPARKING          = Unparking from goal\n"
"string PAUSED             = Paused\n"
"string FINISHED           = Finished\n"
"string OVERCOMING_STATIC  = Overcoming static obstacle\n"
"string OVERCOMING_DYNAMIC = Overcoming dynamic obstacle\n"
"string DETECTED_SIGN      = Detected traffic sign\n"
"string DETECTED_RED       = Detected traffic light RED\n"
"string DETECTED_GREEN     = Detected traffic light GREEN\n"
"string EMERGENCY_STOP     = Emergency stop\n"
"\n"
"string status\n"
"geometry_msgs/PoseStamped base_position\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::iri_adc_msgs::adc_juryAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iri_adc_msgs::adc_juryAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct adc_juryAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iri_adc_msgs::adc_juryAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iri_adc_msgs::adc_juryAction_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::iri_adc_msgs::adc_juryActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::iri_adc_msgs::adc_juryActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::iri_adc_msgs::adc_juryActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IRI_ADC_MSGS_MESSAGE_ADC_JURYACTION_H
