// Generated by gencpp from file iri_adc_msgs/adc_opendrive_nodes.msg
// DO NOT EDIT!


#ifndef IRI_ADC_MSGS_MESSAGE_ADC_OPENDRIVE_NODES_H
#define IRI_ADC_MSGS_MESSAGE_ADC_OPENDRIVE_NODES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace iri_adc_msgs
{
template <class ContainerAllocator>
struct adc_opendrive_nodes_
{
  typedef adc_opendrive_nodes_<ContainerAllocator> Type;

  adc_opendrive_nodes_()
    : header()
    , nodes()  {
    }
  adc_opendrive_nodes_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , nodes(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<uint32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint32_t>> _nodes_type;
  _nodes_type nodes;





  typedef boost::shared_ptr< ::iri_adc_msgs::adc_opendrive_nodes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iri_adc_msgs::adc_opendrive_nodes_<ContainerAllocator> const> ConstPtr;

}; // struct adc_opendrive_nodes_

typedef ::iri_adc_msgs::adc_opendrive_nodes_<std::allocator<void> > adc_opendrive_nodes;

typedef boost::shared_ptr< ::iri_adc_msgs::adc_opendrive_nodes > adc_opendrive_nodesPtr;
typedef boost::shared_ptr< ::iri_adc_msgs::adc_opendrive_nodes const> adc_opendrive_nodesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iri_adc_msgs::adc_opendrive_nodes_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iri_adc_msgs::adc_opendrive_nodes_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iri_adc_msgs::adc_opendrive_nodes_<ContainerAllocator1> & lhs, const ::iri_adc_msgs::adc_opendrive_nodes_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.nodes == rhs.nodes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iri_adc_msgs::adc_opendrive_nodes_<ContainerAllocator1> & lhs, const ::iri_adc_msgs::adc_opendrive_nodes_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iri_adc_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::iri_adc_msgs::adc_opendrive_nodes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iri_adc_msgs::adc_opendrive_nodes_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iri_adc_msgs::adc_opendrive_nodes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iri_adc_msgs::adc_opendrive_nodes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iri_adc_msgs::adc_opendrive_nodes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iri_adc_msgs::adc_opendrive_nodes_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iri_adc_msgs::adc_opendrive_nodes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "845879e7f3dc3631cf0331e34f95edae";
  }

  static const char* value(const ::iri_adc_msgs::adc_opendrive_nodes_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x845879e7f3dc3631ULL;
  static const uint64_t static_value2 = 0xcf0331e34f95edaeULL;
};

template<class ContainerAllocator>
struct DataType< ::iri_adc_msgs::adc_opendrive_nodes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iri_adc_msgs/adc_opendrive_nodes";
  }

  static const char* value(const ::iri_adc_msgs::adc_opendrive_nodes_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iri_adc_msgs::adc_opendrive_nodes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint32[] nodes\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::iri_adc_msgs::adc_opendrive_nodes_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iri_adc_msgs::adc_opendrive_nodes_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.nodes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct adc_opendrive_nodes_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iri_adc_msgs::adc_opendrive_nodes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iri_adc_msgs::adc_opendrive_nodes_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "nodes[]" << std::endl;
    for (size_t i = 0; i < v.nodes.size(); ++i)
    {
      s << indent << "  nodes[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.nodes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IRI_ADC_MSGS_MESSAGE_ADC_OPENDRIVE_NODES_H
