// Generated by gencpp from file iri_adc_msgs/feature.msg
// DO NOT EDIT!


#ifndef IRI_ADC_MSGS_MESSAGE_FEATURE_H
#define IRI_ADC_MSGS_MESSAGE_FEATURE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace iri_adc_msgs
{
template <class ContainerAllocator>
struct feature_
{
  typedef feature_<ContainerAllocator> Type;

  feature_()
    : pose()
    , probability(0.0)
    , type(0)  {
    }
  feature_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , probability(0.0)
    , type(0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef float _probability_type;
  _probability_type probability;

   typedef int32_t _type_type;
  _type_type type;





  typedef boost::shared_ptr< ::iri_adc_msgs::feature_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iri_adc_msgs::feature_<ContainerAllocator> const> ConstPtr;

}; // struct feature_

typedef ::iri_adc_msgs::feature_<std::allocator<void> > feature;

typedef boost::shared_ptr< ::iri_adc_msgs::feature > featurePtr;
typedef boost::shared_ptr< ::iri_adc_msgs::feature const> featureConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iri_adc_msgs::feature_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iri_adc_msgs::feature_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iri_adc_msgs::feature_<ContainerAllocator1> & lhs, const ::iri_adc_msgs::feature_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose &&
    lhs.probability == rhs.probability &&
    lhs.type == rhs.type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iri_adc_msgs::feature_<ContainerAllocator1> & lhs, const ::iri_adc_msgs::feature_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iri_adc_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::iri_adc_msgs::feature_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iri_adc_msgs::feature_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iri_adc_msgs::feature_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iri_adc_msgs::feature_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iri_adc_msgs::feature_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iri_adc_msgs::feature_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iri_adc_msgs::feature_<ContainerAllocator> >
{
  static const char* value()
  {
    return "03a94f020f11a010a1eef2a8da3da4fd";
  }

  static const char* value(const ::iri_adc_msgs::feature_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x03a94f020f11a010ULL;
  static const uint64_t static_value2 = 0xa1eef2a8da3da4fdULL;
};

template<class ContainerAllocator>
struct DataType< ::iri_adc_msgs::feature_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iri_adc_msgs/feature";
  }

  static const char* value(const ::iri_adc_msgs::feature_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iri_adc_msgs::feature_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose pose\n"
"float32 probability\n"
"int32 type\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::iri_adc_msgs::feature_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iri_adc_msgs::feature_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.probability);
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct feature_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iri_adc_msgs::feature_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iri_adc_msgs::feature_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "probability: ";
    Printer<float>::stream(s, indent + "  ", v.probability);
    s << indent << "type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IRI_ADC_MSGS_MESSAGE_FEATURE_H
