// Generated by gencpp from file iri_adc_msgs/feature_array.msg
// DO NOT EDIT!


#ifndef IRI_ADC_MSGS_MESSAGE_FEATURE_ARRAY_H
#define IRI_ADC_MSGS_MESSAGE_FEATURE_ARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <iri_adc_msgs/feature.h>

namespace iri_adc_msgs
{
template <class ContainerAllocator>
struct feature_array_
{
  typedef feature_array_<ContainerAllocator> Type;

  feature_array_()
    : header()
    , features()  {
    }
  feature_array_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , features(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::iri_adc_msgs::feature_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::iri_adc_msgs::feature_<ContainerAllocator> >> _features_type;
  _features_type features;





  typedef boost::shared_ptr< ::iri_adc_msgs::feature_array_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iri_adc_msgs::feature_array_<ContainerAllocator> const> ConstPtr;

}; // struct feature_array_

typedef ::iri_adc_msgs::feature_array_<std::allocator<void> > feature_array;

typedef boost::shared_ptr< ::iri_adc_msgs::feature_array > feature_arrayPtr;
typedef boost::shared_ptr< ::iri_adc_msgs::feature_array const> feature_arrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iri_adc_msgs::feature_array_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iri_adc_msgs::feature_array_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iri_adc_msgs::feature_array_<ContainerAllocator1> & lhs, const ::iri_adc_msgs::feature_array_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.features == rhs.features;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iri_adc_msgs::feature_array_<ContainerAllocator1> & lhs, const ::iri_adc_msgs::feature_array_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iri_adc_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::iri_adc_msgs::feature_array_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iri_adc_msgs::feature_array_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iri_adc_msgs::feature_array_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iri_adc_msgs::feature_array_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iri_adc_msgs::feature_array_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iri_adc_msgs::feature_array_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iri_adc_msgs::feature_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "05b0f044b6c95717caf7d22473f613a5";
  }

  static const char* value(const ::iri_adc_msgs::feature_array_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x05b0f044b6c95717ULL;
  static const uint64_t static_value2 = 0xcaf7d22473f613a5ULL;
};

template<class ContainerAllocator>
struct DataType< ::iri_adc_msgs::feature_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iri_adc_msgs/feature_array";
  }

  static const char* value(const ::iri_adc_msgs::feature_array_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iri_adc_msgs::feature_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header     header\n"
"feature[] features\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: iri_adc_msgs/feature\n"
"geometry_msgs/Pose pose\n"
"float32 probability\n"
"int32 type\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::iri_adc_msgs::feature_array_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iri_adc_msgs::feature_array_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.features);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct feature_array_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iri_adc_msgs::feature_array_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iri_adc_msgs::feature_array_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "features[]" << std::endl;
    for (size_t i = 0; i < v.features.size(); ++i)
    {
      s << indent << "  features[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::iri_adc_msgs::feature_<ContainerAllocator> >::stream(s, indent + "    ", v.features[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IRI_ADC_MSGS_MESSAGE_FEATURE_ARRAY_H
