// Generated by gencpp from file iri_adc_msgs/get_opendrive_map.msg
// DO NOT EDIT!


#ifndef IRI_ADC_MSGS_MESSAGE_GET_OPENDRIVE_MAP_H
#define IRI_ADC_MSGS_MESSAGE_GET_OPENDRIVE_MAP_H

#include <ros/service_traits.h>


#include <iri_adc_msgs/get_opendrive_mapRequest.h>
#include <iri_adc_msgs/get_opendrive_mapResponse.h>


namespace iri_adc_msgs
{

struct get_opendrive_map
{

typedef get_opendrive_mapRequest Request;
typedef get_opendrive_mapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_opendrive_map
} // namespace iri_adc_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::iri_adc_msgs::get_opendrive_map > {
  static const char* value()
  {
    return "803342621a8afb88f3009bae39025db7";
  }

  static const char* value(const ::iri_adc_msgs::get_opendrive_map&) { return value(); }
};

template<>
struct DataType< ::iri_adc_msgs::get_opendrive_map > {
  static const char* value()
  {
    return "iri_adc_msgs/get_opendrive_map";
  }

  static const char* value(const ::iri_adc_msgs::get_opendrive_map&) { return value(); }
};


// service_traits::MD5Sum< ::iri_adc_msgs::get_opendrive_mapRequest> should match
// service_traits::MD5Sum< ::iri_adc_msgs::get_opendrive_map >
template<>
struct MD5Sum< ::iri_adc_msgs::get_opendrive_mapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::iri_adc_msgs::get_opendrive_map >::value();
  }
  static const char* value(const ::iri_adc_msgs::get_opendrive_mapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::iri_adc_msgs::get_opendrive_mapRequest> should match
// service_traits::DataType< ::iri_adc_msgs::get_opendrive_map >
template<>
struct DataType< ::iri_adc_msgs::get_opendrive_mapRequest>
{
  static const char* value()
  {
    return DataType< ::iri_adc_msgs::get_opendrive_map >::value();
  }
  static const char* value(const ::iri_adc_msgs::get_opendrive_mapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::iri_adc_msgs::get_opendrive_mapResponse> should match
// service_traits::MD5Sum< ::iri_adc_msgs::get_opendrive_map >
template<>
struct MD5Sum< ::iri_adc_msgs::get_opendrive_mapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::iri_adc_msgs::get_opendrive_map >::value();
  }
  static const char* value(const ::iri_adc_msgs::get_opendrive_mapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::iri_adc_msgs::get_opendrive_mapResponse> should match
// service_traits::DataType< ::iri_adc_msgs::get_opendrive_map >
template<>
struct DataType< ::iri_adc_msgs::get_opendrive_mapResponse>
{
  static const char* value()
  {
    return DataType< ::iri_adc_msgs::get_opendrive_map >::value();
  }
  static const char* value(const ::iri_adc_msgs::get_opendrive_mapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IRI_ADC_MSGS_MESSAGE_GET_OPENDRIVE_MAP_H
