// Generated by gencpp from file iri_adc_msgs/get_opendrive_nodes.msg
// DO NOT EDIT!


#ifndef IRI_ADC_MSGS_MESSAGE_GET_OPENDRIVE_NODES_H
#define IRI_ADC_MSGS_MESSAGE_GET_OPENDRIVE_NODES_H

#include <ros/service_traits.h>


#include <iri_adc_msgs/get_opendrive_nodesRequest.h>
#include <iri_adc_msgs/get_opendrive_nodesResponse.h>


namespace iri_adc_msgs
{

struct get_opendrive_nodes
{

typedef get_opendrive_nodesRequest Request;
typedef get_opendrive_nodesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_opendrive_nodes
} // namespace iri_adc_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::iri_adc_msgs::get_opendrive_nodes > {
  static const char* value()
  {
    return "5aeb03ca3f6c21b8df58026d567d3563";
  }

  static const char* value(const ::iri_adc_msgs::get_opendrive_nodes&) { return value(); }
};

template<>
struct DataType< ::iri_adc_msgs::get_opendrive_nodes > {
  static const char* value()
  {
    return "iri_adc_msgs/get_opendrive_nodes";
  }

  static const char* value(const ::iri_adc_msgs::get_opendrive_nodes&) { return value(); }
};


// service_traits::MD5Sum< ::iri_adc_msgs::get_opendrive_nodesRequest> should match
// service_traits::MD5Sum< ::iri_adc_msgs::get_opendrive_nodes >
template<>
struct MD5Sum< ::iri_adc_msgs::get_opendrive_nodesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::iri_adc_msgs::get_opendrive_nodes >::value();
  }
  static const char* value(const ::iri_adc_msgs::get_opendrive_nodesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::iri_adc_msgs::get_opendrive_nodesRequest> should match
// service_traits::DataType< ::iri_adc_msgs::get_opendrive_nodes >
template<>
struct DataType< ::iri_adc_msgs::get_opendrive_nodesRequest>
{
  static const char* value()
  {
    return DataType< ::iri_adc_msgs::get_opendrive_nodes >::value();
  }
  static const char* value(const ::iri_adc_msgs::get_opendrive_nodesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::iri_adc_msgs::get_opendrive_nodesResponse> should match
// service_traits::MD5Sum< ::iri_adc_msgs::get_opendrive_nodes >
template<>
struct MD5Sum< ::iri_adc_msgs::get_opendrive_nodesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::iri_adc_msgs::get_opendrive_nodes >::value();
  }
  static const char* value(const ::iri_adc_msgs::get_opendrive_nodesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::iri_adc_msgs::get_opendrive_nodesResponse> should match
// service_traits::DataType< ::iri_adc_msgs::get_opendrive_nodes >
template<>
struct DataType< ::iri_adc_msgs::get_opendrive_nodesResponse>
{
  static const char* value()
  {
    return DataType< ::iri_adc_msgs::get_opendrive_nodes >::value();
  }
  static const char* value(const ::iri_adc_msgs::get_opendrive_nodesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IRI_ADC_MSGS_MESSAGE_GET_OPENDRIVE_NODES_H
