// Generated by gencpp from file iri_adc_msgs/jury_mode.msg
// DO NOT EDIT!


#ifndef IRI_ADC_MSGS_MESSAGE_JURY_MODE_H
#define IRI_ADC_MSGS_MESSAGE_JURY_MODE_H

#include <ros/service_traits.h>


#include <iri_adc_msgs/jury_modeRequest.h>
#include <iri_adc_msgs/jury_modeResponse.h>


namespace iri_adc_msgs
{

struct jury_mode
{

typedef jury_modeRequest Request;
typedef jury_modeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct jury_mode
} // namespace iri_adc_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::iri_adc_msgs::jury_mode > {
  static const char* value()
  {
    return "8c1211af706069c994c06e00eb59ac9e";
  }

  static const char* value(const ::iri_adc_msgs::jury_mode&) { return value(); }
};

template<>
struct DataType< ::iri_adc_msgs::jury_mode > {
  static const char* value()
  {
    return "iri_adc_msgs/jury_mode";
  }

  static const char* value(const ::iri_adc_msgs::jury_mode&) { return value(); }
};


// service_traits::MD5Sum< ::iri_adc_msgs::jury_modeRequest> should match
// service_traits::MD5Sum< ::iri_adc_msgs::jury_mode >
template<>
struct MD5Sum< ::iri_adc_msgs::jury_modeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::iri_adc_msgs::jury_mode >::value();
  }
  static const char* value(const ::iri_adc_msgs::jury_modeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::iri_adc_msgs::jury_modeRequest> should match
// service_traits::DataType< ::iri_adc_msgs::jury_mode >
template<>
struct DataType< ::iri_adc_msgs::jury_modeRequest>
{
  static const char* value()
  {
    return DataType< ::iri_adc_msgs::jury_mode >::value();
  }
  static const char* value(const ::iri_adc_msgs::jury_modeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::iri_adc_msgs::jury_modeResponse> should match
// service_traits::MD5Sum< ::iri_adc_msgs::jury_mode >
template<>
struct MD5Sum< ::iri_adc_msgs::jury_modeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::iri_adc_msgs::jury_mode >::value();
  }
  static const char* value(const ::iri_adc_msgs::jury_modeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::iri_adc_msgs::jury_modeResponse> should match
// service_traits::DataType< ::iri_adc_msgs::jury_mode >
template<>
struct DataType< ::iri_adc_msgs::jury_modeResponse>
{
  static const char* value()
  {
    return DataType< ::iri_adc_msgs::jury_mode >::value();
  }
  static const char* value(const ::iri_adc_msgs::jury_modeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IRI_ADC_MSGS_MESSAGE_JURY_MODE_H
