// Generated by gencpp from file iri_adc_msgs/jury_modeResponse.msg
// DO NOT EDIT!


#ifndef IRI_ADC_MSGS_MESSAGE_JURY_MODERESPONSE_H
#define IRI_ADC_MSGS_MESSAGE_JURY_MODERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iri_adc_msgs
{
template <class ContainerAllocator>
struct jury_modeResponse_
{
  typedef jury_modeResponse_<ContainerAllocator> Type;

  jury_modeResponse_()
    {
    }
  jury_modeResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::iri_adc_msgs::jury_modeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iri_adc_msgs::jury_modeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct jury_modeResponse_

typedef ::iri_adc_msgs::jury_modeResponse_<std::allocator<void> > jury_modeResponse;

typedef boost::shared_ptr< ::iri_adc_msgs::jury_modeResponse > jury_modeResponsePtr;
typedef boost::shared_ptr< ::iri_adc_msgs::jury_modeResponse const> jury_modeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iri_adc_msgs::jury_modeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iri_adc_msgs::jury_modeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace iri_adc_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::iri_adc_msgs::jury_modeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iri_adc_msgs::jury_modeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iri_adc_msgs::jury_modeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iri_adc_msgs::jury_modeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iri_adc_msgs::jury_modeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iri_adc_msgs::jury_modeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iri_adc_msgs::jury_modeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::iri_adc_msgs::jury_modeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::iri_adc_msgs::jury_modeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iri_adc_msgs/jury_modeResponse";
  }

  static const char* value(const ::iri_adc_msgs::jury_modeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iri_adc_msgs::jury_modeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::iri_adc_msgs::jury_modeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iri_adc_msgs::jury_modeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct jury_modeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iri_adc_msgs::jury_modeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::iri_adc_msgs::jury_modeResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // IRI_ADC_MSGS_MESSAGE_JURY_MODERESPONSE_H
