// Generated by gencpp from file iri_adc_msgs/set_semaphore.msg
// DO NOT EDIT!


#ifndef IRI_ADC_MSGS_MESSAGE_SET_SEMAPHORE_H
#define IRI_ADC_MSGS_MESSAGE_SET_SEMAPHORE_H

#include <ros/service_traits.h>


#include <iri_adc_msgs/set_semaphoreRequest.h>
#include <iri_adc_msgs/set_semaphoreResponse.h>


namespace iri_adc_msgs
{

struct set_semaphore
{

typedef set_semaphoreRequest Request;
typedef set_semaphoreResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_semaphore
} // namespace iri_adc_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::iri_adc_msgs::set_semaphore > {
  static const char* value()
  {
    return "3a2c1112df73325ba59340ec2e040a3c";
  }

  static const char* value(const ::iri_adc_msgs::set_semaphore&) { return value(); }
};

template<>
struct DataType< ::iri_adc_msgs::set_semaphore > {
  static const char* value()
  {
    return "iri_adc_msgs/set_semaphore";
  }

  static const char* value(const ::iri_adc_msgs::set_semaphore&) { return value(); }
};


// service_traits::MD5Sum< ::iri_adc_msgs::set_semaphoreRequest> should match
// service_traits::MD5Sum< ::iri_adc_msgs::set_semaphore >
template<>
struct MD5Sum< ::iri_adc_msgs::set_semaphoreRequest>
{
  static const char* value()
  {
    return MD5Sum< ::iri_adc_msgs::set_semaphore >::value();
  }
  static const char* value(const ::iri_adc_msgs::set_semaphoreRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::iri_adc_msgs::set_semaphoreRequest> should match
// service_traits::DataType< ::iri_adc_msgs::set_semaphore >
template<>
struct DataType< ::iri_adc_msgs::set_semaphoreRequest>
{
  static const char* value()
  {
    return DataType< ::iri_adc_msgs::set_semaphore >::value();
  }
  static const char* value(const ::iri_adc_msgs::set_semaphoreRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::iri_adc_msgs::set_semaphoreResponse> should match
// service_traits::MD5Sum< ::iri_adc_msgs::set_semaphore >
template<>
struct MD5Sum< ::iri_adc_msgs::set_semaphoreResponse>
{
  static const char* value()
  {
    return MD5Sum< ::iri_adc_msgs::set_semaphore >::value();
  }
  static const char* value(const ::iri_adc_msgs::set_semaphoreResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::iri_adc_msgs::set_semaphoreResponse> should match
// service_traits::DataType< ::iri_adc_msgs::set_semaphore >
template<>
struct DataType< ::iri_adc_msgs::set_semaphoreResponse>
{
  static const char* value()
  {
    return DataType< ::iri_adc_msgs::set_semaphore >::value();
  }
  static const char* value(const ::iri_adc_msgs::set_semaphoreResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IRI_ADC_MSGS_MESSAGE_SET_SEMAPHORE_H
