// Generated by gencpp from file iri_adc_msgs/set_car_lights.msg
// DO NOT EDIT!


#ifndef IRI_ADC_MSGS_MESSAGE_SET_CAR_LIGHTS_H
#define IRI_ADC_MSGS_MESSAGE_SET_CAR_LIGHTS_H

#include <ros/service_traits.h>


#include <iri_adc_msgs/set_car_lightsRequest.h>
#include <iri_adc_msgs/set_car_lightsResponse.h>


namespace iri_adc_msgs
{

struct set_car_lights
{

typedef set_car_lightsRequest Request;
typedef set_car_lightsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_car_lights
} // namespace iri_adc_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::iri_adc_msgs::set_car_lights > {
  static const char* value()
  {
    return "cbf39d5601e4232b41019dc5a0264ee4";
  }

  static const char* value(const ::iri_adc_msgs::set_car_lights&) { return value(); }
};

template<>
struct DataType< ::iri_adc_msgs::set_car_lights > {
  static const char* value()
  {
    return "iri_adc_msgs/set_car_lights";
  }

  static const char* value(const ::iri_adc_msgs::set_car_lights&) { return value(); }
};


// service_traits::MD5Sum< ::iri_adc_msgs::set_car_lightsRequest> should match
// service_traits::MD5Sum< ::iri_adc_msgs::set_car_lights >
template<>
struct MD5Sum< ::iri_adc_msgs::set_car_lightsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::iri_adc_msgs::set_car_lights >::value();
  }
  static const char* value(const ::iri_adc_msgs::set_car_lightsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::iri_adc_msgs::set_car_lightsRequest> should match
// service_traits::DataType< ::iri_adc_msgs::set_car_lights >
template<>
struct DataType< ::iri_adc_msgs::set_car_lightsRequest>
{
  static const char* value()
  {
    return DataType< ::iri_adc_msgs::set_car_lights >::value();
  }
  static const char* value(const ::iri_adc_msgs::set_car_lightsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::iri_adc_msgs::set_car_lightsResponse> should match
// service_traits::MD5Sum< ::iri_adc_msgs::set_car_lights >
template<>
struct MD5Sum< ::iri_adc_msgs::set_car_lightsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::iri_adc_msgs::set_car_lights >::value();
  }
  static const char* value(const ::iri_adc_msgs::set_car_lightsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::iri_adc_msgs::set_car_lightsResponse> should match
// service_traits::DataType< ::iri_adc_msgs::set_car_lights >
template<>
struct DataType< ::iri_adc_msgs::set_car_lightsResponse>
{
  static const char* value()
  {
    return DataType< ::iri_adc_msgs::set_car_lights >::value();
  }
  static const char* value(const ::iri_adc_msgs::set_car_lightsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IRI_ADC_MSGS_MESSAGE_SET_CAR_LIGHTS_H
