// Generated by gencpp from file iri_adc_msgs/set_goalsRequest.msg
// DO NOT EDIT!


#ifndef IRI_ADC_MSGS_MESSAGE_SET_GOALSREQUEST_H
#define IRI_ADC_MSGS_MESSAGE_SET_GOALSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <iri_adc_msgs/adc_goal_array.h>

namespace iri_adc_msgs
{
template <class ContainerAllocator>
struct set_goalsRequest_
{
  typedef set_goalsRequest_<ContainerAllocator> Type;

  set_goalsRequest_()
    : goals()  {
    }
  set_goalsRequest_(const ContainerAllocator& _alloc)
    : goals(_alloc)  {
  (void)_alloc;
    }



   typedef  ::iri_adc_msgs::adc_goal_array_<ContainerAllocator>  _goals_type;
  _goals_type goals;





  typedef boost::shared_ptr< ::iri_adc_msgs::set_goalsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iri_adc_msgs::set_goalsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct set_goalsRequest_

typedef ::iri_adc_msgs::set_goalsRequest_<std::allocator<void> > set_goalsRequest;

typedef boost::shared_ptr< ::iri_adc_msgs::set_goalsRequest > set_goalsRequestPtr;
typedef boost::shared_ptr< ::iri_adc_msgs::set_goalsRequest const> set_goalsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iri_adc_msgs::set_goalsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iri_adc_msgs::set_goalsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iri_adc_msgs::set_goalsRequest_<ContainerAllocator1> & lhs, const ::iri_adc_msgs::set_goalsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.goals == rhs.goals;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iri_adc_msgs::set_goalsRequest_<ContainerAllocator1> & lhs, const ::iri_adc_msgs::set_goalsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iri_adc_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::iri_adc_msgs::set_goalsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iri_adc_msgs::set_goalsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iri_adc_msgs::set_goalsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iri_adc_msgs::set_goalsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iri_adc_msgs::set_goalsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iri_adc_msgs::set_goalsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iri_adc_msgs::set_goalsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0dcf3a4de3a9fd4fc109b76f00265887";
  }

  static const char* value(const ::iri_adc_msgs::set_goalsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0dcf3a4de3a9fd4fULL;
  static const uint64_t static_value2 = 0xc109b76f00265887ULL;
};

template<class ContainerAllocator>
struct DataType< ::iri_adc_msgs::set_goalsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iri_adc_msgs/set_goalsRequest";
  }

  static const char* value(const ::iri_adc_msgs::set_goalsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iri_adc_msgs::set_goalsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "adc_goal_array goals\n"
"\n"
"================================================================================\n"
"MSG: iri_adc_msgs/adc_goal_array\n"
"Header     header\n"
"adc_goal[] goals\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: iri_adc_msgs/adc_goal\n"
"#type definitions\n"
"uint8 PASSTHROUGH_GOAL=0\n"
"uint8 STOP_GOAL=1\n"
"uint8 PARKING_GOAL=2\n"
"\n"
"string id       # goal identifier\n"
"float32 x       # x coordinates in meters [m]\n"
"float32 y       # y coordinate in meters [m]\n"
"float32 yaw     # yaw orientation in radians [rad]\n"
"int32 type      # see type definitions above\n"
;
  }

  static const char* value(const ::iri_adc_msgs::set_goalsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iri_adc_msgs::set_goalsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goals);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_goalsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iri_adc_msgs::set_goalsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iri_adc_msgs::set_goalsRequest_<ContainerAllocator>& v)
  {
    s << indent << "goals: ";
    s << std::endl;
    Printer< ::iri_adc_msgs::adc_goal_array_<ContainerAllocator> >::stream(s, indent + "  ", v.goals);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IRI_ADC_MSGS_MESSAGE_SET_GOALSREQUEST_H
