// Generated by gencpp from file iri_model_car_msgs/encoders.msg
// DO NOT EDIT!


#ifndef IRI_MODEL_CAR_MSGS_MESSAGE_ENCODERS_H
#define IRI_MODEL_CAR_MSGS_MESSAGE_ENCODERS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace iri_model_car_msgs
{
template <class ContainerAllocator>
struct encoders_
{
  typedef encoders_<ContainerAllocator> Type;

  encoders_()
    : header()
    , left_ticks(0)
    , left_forward(false)
    , right_ticks(0)
    , right_forward(false)  {
    }
  encoders_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left_ticks(0)
    , left_forward(false)
    , right_ticks(0)
    , right_forward(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _left_ticks_type;
  _left_ticks_type left_ticks;

   typedef uint8_t _left_forward_type;
  _left_forward_type left_forward;

   typedef int32_t _right_ticks_type;
  _right_ticks_type right_ticks;

   typedef uint8_t _right_forward_type;
  _right_forward_type right_forward;





  typedef boost::shared_ptr< ::iri_model_car_msgs::encoders_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iri_model_car_msgs::encoders_<ContainerAllocator> const> ConstPtr;

}; // struct encoders_

typedef ::iri_model_car_msgs::encoders_<std::allocator<void> > encoders;

typedef boost::shared_ptr< ::iri_model_car_msgs::encoders > encodersPtr;
typedef boost::shared_ptr< ::iri_model_car_msgs::encoders const> encodersConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iri_model_car_msgs::encoders_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iri_model_car_msgs::encoders_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iri_model_car_msgs::encoders_<ContainerAllocator1> & lhs, const ::iri_model_car_msgs::encoders_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.left_ticks == rhs.left_ticks &&
    lhs.left_forward == rhs.left_forward &&
    lhs.right_ticks == rhs.right_ticks &&
    lhs.right_forward == rhs.right_forward;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iri_model_car_msgs::encoders_<ContainerAllocator1> & lhs, const ::iri_model_car_msgs::encoders_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iri_model_car_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::iri_model_car_msgs::encoders_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iri_model_car_msgs::encoders_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iri_model_car_msgs::encoders_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iri_model_car_msgs::encoders_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iri_model_car_msgs::encoders_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iri_model_car_msgs::encoders_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iri_model_car_msgs::encoders_<ContainerAllocator> >
{
  static const char* value()
  {
    return "04e73434e714ecf842b1891215a2b24e";
  }

  static const char* value(const ::iri_model_car_msgs::encoders_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x04e73434e714ecf8ULL;
  static const uint64_t static_value2 = 0x42b1891215a2b24eULL;
};

template<class ContainerAllocator>
struct DataType< ::iri_model_car_msgs::encoders_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iri_model_car_msgs/encoders";
  }

  static const char* value(const ::iri_model_car_msgs::encoders_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iri_model_car_msgs::encoders_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 left_ticks\n"
"bool left_forward\n"
"int32 right_ticks\n"
"bool right_forward\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::iri_model_car_msgs::encoders_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iri_model_car_msgs::encoders_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left_ticks);
      stream.next(m.left_forward);
      stream.next(m.right_ticks);
      stream.next(m.right_forward);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct encoders_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iri_model_car_msgs::encoders_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iri_model_car_msgs::encoders_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left_ticks: ";
    Printer<int32_t>::stream(s, indent + "  ", v.left_ticks);
    s << indent << "left_forward: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left_forward);
    s << indent << "right_ticks: ";
    Printer<int32_t>::stream(s, indent + "  ", v.right_ticks);
    s << indent << "right_forward: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_forward);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IRI_MODEL_CAR_MSGS_MESSAGE_ENCODERS_H
