(cl:defpackage iri_adc_msgs-msg
  (:use )
  (:export
   "<ADC_GOAL>"
   "ADC_GOAL"
   "<ADC_GOAL_ARRAY>"
   "ADC_GOAL_ARRAY"
   "<ADC_JURYACTION>"
   "ADC_JURYACTION"
   "<ADC_JURYACTIONFEEDBACK>"
   "ADC_JURYACTIONFEEDBACK"
   "<ADC_JURYACTIONGOAL>"
   "ADC_JURYACTIONGOAL"
   "<ADC_JURYACTIONRESULT>"
   "ADC_JURYACTIONRESULT"
   "<ADC_JURYFEEDBACK>"
   "ADC_JURYFEEDBACK"
   "<ADC_JURYGOAL>"
   "ADC_JURYGOAL"
   "<ADC_JURYRESULT>"
   "ADC_JURYRESULT"
   "<ADC_OPENDRIVE_NODES>"
   "ADC_OPENDRIVE_NODES"
   "<FEATURE>"
   "FEATURE"
   "<FEATURE_ARRAY>"
   "FEATURE_ARRAY"
  ))

