; Auto-generated. Do not edit!


(cl:in-package iri_adc_msgs-msg)


;//! \htmlinclude adc_juryResult.msg.html

(cl:defclass <adc_juryResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass adc_juryResult (<adc_juryResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <adc_juryResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'adc_juryResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name iri_adc_msgs-msg:<adc_juryResult> is deprecated: use iri_adc_msgs-msg:adc_juryResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <adc_juryResult>) ostream)
  "Serializes a message object of type '<adc_juryResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <adc_juryResult>) istream)
  "Deserializes a message object of type '<adc_juryResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<adc_juryResult>)))
  "Returns string type for a message object of type '<adc_juryResult>"
  "iri_adc_msgs/adc_juryResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'adc_juryResult)))
  "Returns string type for a message object of type 'adc_juryResult"
  "iri_adc_msgs/adc_juryResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<adc_juryResult>)))
  "Returns md5sum for a message object of type '<adc_juryResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'adc_juryResult)))
  "Returns md5sum for a message object of type 'adc_juryResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<adc_juryResult>)))
  "Returns full string definition for message of type '<adc_juryResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'adc_juryResult)))
  "Returns full string definition for message of type 'adc_juryResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <adc_juryResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <adc_juryResult>))
  "Converts a ROS message object to a list"
  (cl:list 'adc_juryResult
))
