//#line 2 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the iri_ackermann_local_planner package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __iri_ackermann_local_planner__ACKERMANNLOCALPLANNERCONFIG_H__
#define __iri_ackermann_local_planner__ACKERMANNLOCALPLANNERCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace iri_ackermann_local_planner
{
  class AckermannLocalPlannerConfigStatics;

  class AckermannLocalPlannerConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(AckermannLocalPlannerConfig &config, const AckermannLocalPlannerConfig &max, const AckermannLocalPlannerConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const AckermannLocalPlannerConfig &config1, const AckermannLocalPlannerConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, AckermannLocalPlannerConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const AckermannLocalPlannerConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, AckermannLocalPlannerConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const AckermannLocalPlannerConfig &config) const = 0;
      virtual void getValue(const AckermannLocalPlannerConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T AckermannLocalPlannerConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T AckermannLocalPlannerConfig::* field;

      virtual void clamp(AckermannLocalPlannerConfig &config, const AckermannLocalPlannerConfig &max, const AckermannLocalPlannerConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const AckermannLocalPlannerConfig &config1, const AckermannLocalPlannerConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, AckermannLocalPlannerConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const AckermannLocalPlannerConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, AckermannLocalPlannerConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const AckermannLocalPlannerConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const AckermannLocalPlannerConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, AckermannLocalPlannerConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, AckermannLocalPlannerConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<AckermannLocalPlannerConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(AckermannLocalPlannerConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("max_sim_time"==(*_i)->name){max_sim_time = boost::any_cast<double>(val);}
        if("min_sim_time"==(*_i)->name){min_sim_time = boost::any_cast<double>(val);}
        if("sim_granularity"==(*_i)->name){sim_granularity = boost::any_cast<double>(val);}
        if("angular_sim_granularity"==(*_i)->name){angular_sim_granularity = boost::any_cast<double>(val);}
        if("path_distance_bias"==(*_i)->name){path_distance_bias = boost::any_cast<double>(val);}
        if("goal_distance_bias"==(*_i)->name){goal_distance_bias = boost::any_cast<double>(val);}
        if("occdist_scale"==(*_i)->name){occdist_scale = boost::any_cast<double>(val);}
        if("stop_time_buffer"==(*_i)->name){stop_time_buffer = boost::any_cast<double>(val);}
        if("oscillation_reset_dist"==(*_i)->name){oscillation_reset_dist = boost::any_cast<double>(val);}
        if("oscillation_reset_angle"==(*_i)->name){oscillation_reset_angle = boost::any_cast<double>(val);}
        if("forward_point_distance"==(*_i)->name){forward_point_distance = boost::any_cast<double>(val);}
        if("scaling_speed"==(*_i)->name){scaling_speed = boost::any_cast<double>(val);}
        if("max_scaling_factor"==(*_i)->name){max_scaling_factor = boost::any_cast<double>(val);}
        if("trans_vel_samples"==(*_i)->name){trans_vel_samples = boost::any_cast<int>(val);}
        if("steer_angle_samples"==(*_i)->name){steer_angle_samples = boost::any_cast<int>(val);}
        if("angular_vel_samples"==(*_i)->name){angular_vel_samples = boost::any_cast<int>(val);}
        if("use_steer_angle_cmd"==(*_i)->name){use_steer_angle_cmd = boost::any_cast<bool>(val);}
        if("invert_steer_angle_cmd"==(*_i)->name){invert_steer_angle_cmd = boost::any_cast<bool>(val);}
        if("use_stopped_steering"==(*_i)->name){use_stopped_steering = boost::any_cast<bool>(val);}
        if("stopped_steering_angle_threshold"==(*_i)->name){stopped_steering_angle_threshold = boost::any_cast<double>(val);}
        if("use_stuck_check"==(*_i)->name){use_stuck_check = boost::any_cast<bool>(val);}
        if("stuck_check_vel_threshold"==(*_i)->name){stuck_check_vel_threshold = boost::any_cast<double>(val);}
        if("stuck_check_max_occurrences"==(*_i)->name){stuck_check_max_occurrences = boost::any_cast<int>(val);}
        if("prune_plan"==(*_i)->name){prune_plan = boost::any_cast<bool>(val);}
        if("xy_goal_tolerance"==(*_i)->name){xy_goal_tolerance = boost::any_cast<double>(val);}
        if("yaw_goal_tolerance"==(*_i)->name){yaw_goal_tolerance = boost::any_cast<double>(val);}
        if("trans_stopped_vel"==(*_i)->name){trans_stopped_vel = boost::any_cast<double>(val);}
        if("rot_stopped_vel"==(*_i)->name){rot_stopped_vel = boost::any_cast<double>(val);}
        if("restore_defaults"==(*_i)->name){restore_defaults = boost::any_cast<bool>(val);}
        if("max_trans_vel"==(*_i)->name){max_trans_vel = boost::any_cast<double>(val);}
        if("min_trans_vel"==(*_i)->name){min_trans_vel = boost::any_cast<double>(val);}
        if("max_trans_acc"==(*_i)->name){max_trans_acc = boost::any_cast<double>(val);}
        if("max_steer_angle"==(*_i)->name){max_steer_angle = boost::any_cast<double>(val);}
        if("min_steer_angle"==(*_i)->name){min_steer_angle = boost::any_cast<double>(val);}
        if("max_steer_vel"==(*_i)->name){max_steer_vel = boost::any_cast<double>(val);}
        if("min_steer_vel"==(*_i)->name){min_steer_vel = boost::any_cast<double>(val);}
        if("max_steer_acc"==(*_i)->name){max_steer_acc = boost::any_cast<double>(val);}
        if("max_angular_vel"==(*_i)->name){max_angular_vel = boost::any_cast<double>(val);}
        if("min_angular_vel"==(*_i)->name){min_angular_vel = boost::any_cast<double>(val);}
        if("axis_distance"==(*_i)->name){axis_distance = boost::any_cast<double>(val);}
        if("wheel_distance"==(*_i)->name){wheel_distance = boost::any_cast<double>(val);}
        if("wheel_radius"==(*_i)->name){wheel_radius = boost::any_cast<double>(val);}
        if("use_trans_vel_deadzone"==(*_i)->name){use_trans_vel_deadzone = boost::any_cast<bool>(val);}
        if("trans_vel_deadzone"==(*_i)->name){trans_vel_deadzone = boost::any_cast<double>(val);}
        if("split_ignore_length"==(*_i)->name){split_ignore_length = boost::any_cast<double>(val);}
        if("cmd_vel_avg"==(*_i)->name){cmd_vel_avg = boost::any_cast<int>(val);}
        if("odom_avg"==(*_i)->name){odom_avg = boost::any_cast<int>(val);}
        if("planner_patience"==(*_i)->name){planner_patience = boost::any_cast<int>(val);}
        if("hdiff_scale"==(*_i)->name){hdiff_scale = boost::any_cast<double>(val);}
        if("heading_points"==(*_i)->name){heading_points = boost::any_cast<int>(val);}
      }
    }

    double max_sim_time;
double min_sim_time;
double sim_granularity;
double angular_sim_granularity;
double path_distance_bias;
double goal_distance_bias;
double occdist_scale;
double stop_time_buffer;
double oscillation_reset_dist;
double oscillation_reset_angle;
double forward_point_distance;
double scaling_speed;
double max_scaling_factor;
int trans_vel_samples;
int steer_angle_samples;
int angular_vel_samples;
bool use_steer_angle_cmd;
bool invert_steer_angle_cmd;
bool use_stopped_steering;
double stopped_steering_angle_threshold;
bool use_stuck_check;
double stuck_check_vel_threshold;
int stuck_check_max_occurrences;
bool prune_plan;
double xy_goal_tolerance;
double yaw_goal_tolerance;
double trans_stopped_vel;
double rot_stopped_vel;
bool restore_defaults;
double max_trans_vel;
double min_trans_vel;
double max_trans_acc;
double max_steer_angle;
double min_steer_angle;
double max_steer_vel;
double min_steer_vel;
double max_steer_acc;
double max_angular_vel;
double min_angular_vel;
double axis_distance;
double wheel_distance;
double wheel_radius;
bool use_trans_vel_deadzone;
double trans_vel_deadzone;
double split_ignore_length;
int cmd_vel_avg;
int odom_avg;
int planner_patience;
double hdiff_scale;
int heading_points;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_sim_time;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_sim_time;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double sim_granularity;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double angular_sim_granularity;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double path_distance_bias;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double goal_distance_bias;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double occdist_scale;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double stop_time_buffer;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double oscillation_reset_dist;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double oscillation_reset_angle;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double forward_point_distance;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double scaling_speed;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_scaling_factor;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int trans_vel_samples;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int steer_angle_samples;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int angular_vel_samples;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool use_steer_angle_cmd;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool invert_steer_angle_cmd;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool use_stopped_steering;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double stopped_steering_angle_threshold;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool use_stuck_check;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double stuck_check_vel_threshold;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int stuck_check_max_occurrences;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool prune_plan;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double xy_goal_tolerance;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double yaw_goal_tolerance;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double trans_stopped_vel;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double rot_stopped_vel;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool restore_defaults;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_trans_vel;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_trans_vel;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_trans_acc;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_steer_angle;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_steer_angle;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_steer_vel;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_steer_vel;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_steer_acc;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_angular_vel;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_angular_vel;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double axis_distance;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double wheel_distance;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double wheel_radius;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool use_trans_vel_deadzone;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double trans_vel_deadzone;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double split_ignore_length;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int cmd_vel_avg;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int odom_avg;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int planner_patience;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double hdiff_scale;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int heading_points;
//#line 228 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("AckermannLocalPlannerConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const AckermannLocalPlannerConfig &__max__ = __getMax__();
      const AckermannLocalPlannerConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const AckermannLocalPlannerConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const AckermannLocalPlannerConfig &__getDefault__();
    static const AckermannLocalPlannerConfig &__getMax__();
    static const AckermannLocalPlannerConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const AckermannLocalPlannerConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void AckermannLocalPlannerConfig::ParamDescription<std::string>::clamp(AckermannLocalPlannerConfig &config, const AckermannLocalPlannerConfig &max, const AckermannLocalPlannerConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class AckermannLocalPlannerConfigStatics
  {
    friend class AckermannLocalPlannerConfig;

    AckermannLocalPlannerConfigStatics()
    {
AckermannLocalPlannerConfig::GroupDescription<AckermannLocalPlannerConfig::DEFAULT, AckermannLocalPlannerConfig> Default("Default", "", 0, 0, true, &AckermannLocalPlannerConfig::groups);
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_sim_time = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_sim_time = 20.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_sim_time = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("max_sim_time", "double", 0, "The amount of time to roll trajectories out for in seconds", "", &AckermannLocalPlannerConfig::max_sim_time)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("max_sim_time", "double", 0, "The amount of time to roll trajectories out for in seconds", "", &AckermannLocalPlannerConfig::max_sim_time)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_sim_time = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_sim_time = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_sim_time = 1.7;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("min_sim_time", "double", 0, "The amount of time to roll trajectories out for in seconds", "", &AckermannLocalPlannerConfig::min_sim_time)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("min_sim_time", "double", 0, "The amount of time to roll trajectories out for in seconds", "", &AckermannLocalPlannerConfig::min_sim_time)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.sim_granularity = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.sim_granularity = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.sim_granularity = 0.025;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("sim_granularity", "double", 0, "The granularity with which to check for collisions along each trajectory in meters", "", &AckermannLocalPlannerConfig::sim_granularity)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("sim_granularity", "double", 0, "The granularity with which to check for collisions along each trajectory in meters", "", &AckermannLocalPlannerConfig::sim_granularity)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.angular_sim_granularity = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.angular_sim_granularity = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.angular_sim_granularity = 0.1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("angular_sim_granularity", "double", 0, "The granularity with which to check for collisions for rotations in radians", "", &AckermannLocalPlannerConfig::angular_sim_granularity)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("angular_sim_granularity", "double", 0, "The granularity with which to check for collisions for rotations in radians", "", &AckermannLocalPlannerConfig::angular_sim_granularity)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.path_distance_bias = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.path_distance_bias = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.path_distance_bias = 32.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("path_distance_bias", "double", 0, "The weight for the path distance part of the cost function", "", &AckermannLocalPlannerConfig::path_distance_bias)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("path_distance_bias", "double", 0, "The weight for the path distance part of the cost function", "", &AckermannLocalPlannerConfig::path_distance_bias)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.goal_distance_bias = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.goal_distance_bias = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.goal_distance_bias = 24.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("goal_distance_bias", "double", 0, "The weight for the goal distance part of the cost function", "", &AckermannLocalPlannerConfig::goal_distance_bias)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("goal_distance_bias", "double", 0, "The weight for the goal distance part of the cost function", "", &AckermannLocalPlannerConfig::goal_distance_bias)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.occdist_scale = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.occdist_scale = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.occdist_scale = 0.01;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("occdist_scale", "double", 0, "The weight for the obstacle distance part of the cost function", "", &AckermannLocalPlannerConfig::occdist_scale)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("occdist_scale", "double", 0, "The weight for the obstacle distance part of the cost function", "", &AckermannLocalPlannerConfig::occdist_scale)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.stop_time_buffer = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.stop_time_buffer = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.stop_time_buffer = 0.2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("stop_time_buffer", "double", 0, "The amount of time that the robot must stop before a collision in order for a trajectory to be considered valid in seconds", "", &AckermannLocalPlannerConfig::stop_time_buffer)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("stop_time_buffer", "double", 0, "The amount of time that the robot must stop before a collision in order for a trajectory to be considered valid in seconds", "", &AckermannLocalPlannerConfig::stop_time_buffer)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.oscillation_reset_dist = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.oscillation_reset_dist = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.oscillation_reset_dist = 0.05;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("oscillation_reset_dist", "double", 0, "The distance the robot must travel before oscillation flags are reset, in meters", "", &AckermannLocalPlannerConfig::oscillation_reset_dist)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("oscillation_reset_dist", "double", 0, "The distance the robot must travel before oscillation flags are reset, in meters", "", &AckermannLocalPlannerConfig::oscillation_reset_dist)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.oscillation_reset_angle = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.oscillation_reset_angle = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.oscillation_reset_angle = 0.2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("oscillation_reset_angle", "double", 0, "The angle the robot must turn before oscillation flags are reset, in radians", "", &AckermannLocalPlannerConfig::oscillation_reset_angle)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("oscillation_reset_angle", "double", 0, "The angle the robot must turn before oscillation flags are reset, in radians", "", &AckermannLocalPlannerConfig::oscillation_reset_angle)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.forward_point_distance = -std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.forward_point_distance = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.forward_point_distance = 0.325;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("forward_point_distance", "double", 0, "The distance from the center point of the robot to place an additional scoring point, in meters", "", &AckermannLocalPlannerConfig::forward_point_distance)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("forward_point_distance", "double", 0, "The distance from the center point of the robot to place an additional scoring point, in meters", "", &AckermannLocalPlannerConfig::forward_point_distance)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.scaling_speed = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.scaling_speed = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.scaling_speed = 0.25;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("scaling_speed", "double", 0, "The absolute value of the velocity at which to start scaling the robot's footprint, in m/s", "", &AckermannLocalPlannerConfig::scaling_speed)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("scaling_speed", "double", 0, "The absolute value of the velocity at which to start scaling the robot's footprint, in m/s", "", &AckermannLocalPlannerConfig::scaling_speed)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_scaling_factor = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_scaling_factor = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_scaling_factor = 0.2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("max_scaling_factor", "double", 0, "The maximum factor to scale the robot's footprint by", "", &AckermannLocalPlannerConfig::max_scaling_factor)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("max_scaling_factor", "double", 0, "The maximum factor to scale the robot's footprint by", "", &AckermannLocalPlannerConfig::max_scaling_factor)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.trans_vel_samples = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.trans_vel_samples = 2147483647;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.trans_vel_samples = 3;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<int>("trans_vel_samples", "int", 0, "The number of samples to use when exploring the x velocity space", "", &AckermannLocalPlannerConfig::trans_vel_samples)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<int>("trans_vel_samples", "int", 0, "The number of samples to use when exploring the x velocity space", "", &AckermannLocalPlannerConfig::trans_vel_samples)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.steer_angle_samples = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.steer_angle_samples = 2147483647;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.steer_angle_samples = 10;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<int>("steer_angle_samples", "int", 0, "The number of samples to use when exploring the steer angle space", "", &AckermannLocalPlannerConfig::steer_angle_samples)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<int>("steer_angle_samples", "int", 0, "The number of samples to use when exploring the steer angle space", "", &AckermannLocalPlannerConfig::steer_angle_samples)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.angular_vel_samples = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.angular_vel_samples = 2147483647;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.angular_vel_samples = 10;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<int>("angular_vel_samples", "int", 0, "The number of samples to use when exploring the angular velocity space", "", &AckermannLocalPlannerConfig::angular_vel_samples)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<int>("angular_vel_samples", "int", 0, "The number of samples to use when exploring the angular velocity space", "", &AckermannLocalPlannerConfig::angular_vel_samples)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.use_steer_angle_cmd = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.use_steer_angle_cmd = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.use_steer_angle_cmd = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<bool>("use_steer_angle_cmd", "bool", 0, "Whether to use the steer angle or the angular velocity.", "", &AckermannLocalPlannerConfig::use_steer_angle_cmd)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<bool>("use_steer_angle_cmd", "bool", 0, "Whether to use the steer angle or the angular velocity.", "", &AckermannLocalPlannerConfig::use_steer_angle_cmd)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.invert_steer_angle_cmd = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.invert_steer_angle_cmd = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.invert_steer_angle_cmd = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<bool>("invert_steer_angle_cmd", "bool", 0, "Whether to use the invert the steer angle command or not.", "", &AckermannLocalPlannerConfig::invert_steer_angle_cmd)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<bool>("invert_steer_angle_cmd", "bool", 0, "Whether to use the invert the steer angle command or not.", "", &AckermannLocalPlannerConfig::invert_steer_angle_cmd)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.use_stopped_steering = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.use_stopped_steering = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.use_stopped_steering = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<bool>("use_stopped_steering", "bool", 0, "Whether to allow steering while stopped or not.", "", &AckermannLocalPlannerConfig::use_stopped_steering)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<bool>("use_stopped_steering", "bool", 0, "Whether to allow steering while stopped or not.", "", &AckermannLocalPlannerConfig::use_stopped_steering)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.stopped_steering_angle_threshold = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.stopped_steering_angle_threshold = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.stopped_steering_angle_threshold = 0.05;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("stopped_steering_angle_threshold", "double", 0, "Angle difference threshold (rad) to perform steering change while stopped.", "", &AckermannLocalPlannerConfig::stopped_steering_angle_threshold)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("stopped_steering_angle_threshold", "double", 0, "Angle difference threshold (rad) to perform steering change while stopped.", "", &AckermannLocalPlannerConfig::stopped_steering_angle_threshold)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.use_stuck_check = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.use_stuck_check = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.use_stuck_check = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<bool>("use_stuck_check", "bool", 0, "Whether to allow robot stuck check or not.", "", &AckermannLocalPlannerConfig::use_stuck_check)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<bool>("use_stuck_check", "bool", 0, "Whether to allow robot stuck check or not.", "", &AckermannLocalPlannerConfig::use_stuck_check)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.stuck_check_vel_threshold = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.stuck_check_vel_threshold = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.stuck_check_vel_threshold = 0.05;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("stuck_check_vel_threshold", "double", 0, "Velocity threshold (m/s) to consider robot stuck.", "", &AckermannLocalPlannerConfig::stuck_check_vel_threshold)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("stuck_check_vel_threshold", "double", 0, "Velocity threshold (m/s) to consider robot stuck.", "", &AckermannLocalPlannerConfig::stuck_check_vel_threshold)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.stuck_check_max_occurrences = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.stuck_check_max_occurrences = 2147483647;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.stuck_check_max_occurrences = 10;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<int>("stuck_check_max_occurrences", "int", 0, "Max number of stuck occurrences allowed until moving to next segment or replaning.", "", &AckermannLocalPlannerConfig::stuck_check_max_occurrences)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<int>("stuck_check_max_occurrences", "int", 0, "Max number of stuck occurrences allowed until moving to next segment or replaning.", "", &AckermannLocalPlannerConfig::stuck_check_max_occurrences)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.prune_plan = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.prune_plan = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.prune_plan = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<bool>("prune_plan", "bool", 0, "Start following closest point of global plan, not first point (if different).", "", &AckermannLocalPlannerConfig::prune_plan)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<bool>("prune_plan", "bool", 0, "Start following closest point of global plan, not first point (if different).", "", &AckermannLocalPlannerConfig::prune_plan)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.xy_goal_tolerance = -std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.xy_goal_tolerance = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.xy_goal_tolerance = 0.1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("xy_goal_tolerance", "double", 0, "Within what maximum distance we consider the robot to be in goal", "", &AckermannLocalPlannerConfig::xy_goal_tolerance)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("xy_goal_tolerance", "double", 0, "Within what maximum distance we consider the robot to be in goal", "", &AckermannLocalPlannerConfig::xy_goal_tolerance)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.yaw_goal_tolerance = -std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.yaw_goal_tolerance = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.yaw_goal_tolerance = 0.1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("yaw_goal_tolerance", "double", 0, "Within what maximum angle difference we consider the robot to face goal direction", "", &AckermannLocalPlannerConfig::yaw_goal_tolerance)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("yaw_goal_tolerance", "double", 0, "Within what maximum angle difference we consider the robot to face goal direction", "", &AckermannLocalPlannerConfig::yaw_goal_tolerance)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.trans_stopped_vel = -std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.trans_stopped_vel = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.trans_stopped_vel = 0.1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("trans_stopped_vel", "double", 0, "Below what maximum velocity we consider the robot to be stopped in translation", "", &AckermannLocalPlannerConfig::trans_stopped_vel)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("trans_stopped_vel", "double", 0, "Below what maximum velocity we consider the robot to be stopped in translation", "", &AckermannLocalPlannerConfig::trans_stopped_vel)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.rot_stopped_vel = -std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.rot_stopped_vel = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.rot_stopped_vel = 0.1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("rot_stopped_vel", "double", 0, "Below what maximum rotation velocity we consider the robot to be stopped in rotation", "", &AckermannLocalPlannerConfig::rot_stopped_vel)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("rot_stopped_vel", "double", 0, "Below what maximum rotation velocity we consider the robot to be stopped in rotation", "", &AckermannLocalPlannerConfig::rot_stopped_vel)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.restore_defaults = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.restore_defaults = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.restore_defaults = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<bool>("restore_defaults", "bool", 0, "Restore to the original configuration.", "", &AckermannLocalPlannerConfig::restore_defaults)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<bool>("restore_defaults", "bool", 0, "Restore to the original configuration.", "", &AckermannLocalPlannerConfig::restore_defaults)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_trans_vel = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_trans_vel = 20.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_trans_vel = 0.3;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("max_trans_vel", "double", 0, "maximum translational speed", "", &AckermannLocalPlannerConfig::max_trans_vel)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("max_trans_vel", "double", 0, "maximum translational speed", "", &AckermannLocalPlannerConfig::max_trans_vel)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_trans_vel = -20.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_trans_vel = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_trans_vel = -0.3;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("min_trans_vel", "double", 0, "minimum translational speed", "", &AckermannLocalPlannerConfig::min_trans_vel)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("min_trans_vel", "double", 0, "minimum translational speed", "", &AckermannLocalPlannerConfig::min_trans_vel)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_trans_acc = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_trans_acc = 20.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_trans_acc = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("max_trans_acc", "double", 0, "maximum translational acceleration", "", &AckermannLocalPlannerConfig::max_trans_acc)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("max_trans_acc", "double", 0, "maximum translational acceleration", "", &AckermannLocalPlannerConfig::max_trans_acc)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_steer_angle = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_steer_angle = 0.54;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_steer_angle = 0.45;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("max_steer_angle", "double", 0, "maximum steer angle", "", &AckermannLocalPlannerConfig::max_steer_angle)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("max_steer_angle", "double", 0, "maximum steer angle", "", &AckermannLocalPlannerConfig::max_steer_angle)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_steer_angle = -0.54;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_steer_angle = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_steer_angle = -0.45;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("min_steer_angle", "double", 0, "minimum steer angle", "", &AckermannLocalPlannerConfig::min_steer_angle)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("min_steer_angle", "double", 0, "minimum steer angle", "", &AckermannLocalPlannerConfig::min_steer_angle)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_steer_vel = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_steer_vel = 2.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_steer_vel = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("max_steer_vel", "double", 0, "maximum steer speed", "", &AckermannLocalPlannerConfig::max_steer_vel)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("max_steer_vel", "double", 0, "maximum steer speed", "", &AckermannLocalPlannerConfig::max_steer_vel)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_steer_vel = -2.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_steer_vel = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_steer_vel = -1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("min_steer_vel", "double", 0, "minimum steer speed", "", &AckermannLocalPlannerConfig::min_steer_vel)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("min_steer_vel", "double", 0, "minimum steer speed", "", &AckermannLocalPlannerConfig::min_steer_vel)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_steer_acc = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_steer_acc = 5.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_steer_acc = 0.36;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("max_steer_acc", "double", 0, "maximum steer acceleration", "", &AckermannLocalPlannerConfig::max_steer_acc)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("max_steer_acc", "double", 0, "maximum steer acceleration", "", &AckermannLocalPlannerConfig::max_steer_acc)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_angular_vel = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_angular_vel = 20.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_angular_vel = 0.3;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("max_angular_vel", "double", 0, "maximum angular speed", "", &AckermannLocalPlannerConfig::max_angular_vel)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("max_angular_vel", "double", 0, "maximum angular speed", "", &AckermannLocalPlannerConfig::max_angular_vel)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_angular_vel = -20.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_angular_vel = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_angular_vel = -0.3;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("min_angular_vel", "double", 0, "minimum angular speed", "", &AckermannLocalPlannerConfig::min_angular_vel)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("min_angular_vel", "double", 0, "minimum angular speed", "", &AckermannLocalPlannerConfig::min_angular_vel)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.axis_distance = -2.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.axis_distance = 2.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.axis_distance = 1.65;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("axis_distance", "double", 0, "distance between axes", "", &AckermannLocalPlannerConfig::axis_distance)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("axis_distance", "double", 0, "distance between axes", "", &AckermannLocalPlannerConfig::axis_distance)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.wheel_distance = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.wheel_distance = 2.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.wheel_distance = 1.2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("wheel_distance", "double", 0, "distance between wheels", "", &AckermannLocalPlannerConfig::wheel_distance)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("wheel_distance", "double", 0, "distance between wheels", "", &AckermannLocalPlannerConfig::wheel_distance)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.wheel_radius = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.wheel_radius = 2.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.wheel_radius = 0.436;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("wheel_radius", "double", 0, "Wheel diameter", "", &AckermannLocalPlannerConfig::wheel_radius)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("wheel_radius", "double", 0, "Wheel diameter", "", &AckermannLocalPlannerConfig::wheel_radius)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.use_trans_vel_deadzone = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.use_trans_vel_deadzone = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.use_trans_vel_deadzone = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<bool>("use_trans_vel_deadzone", "bool", 0, "Whether to use a deadzone in the translational velocity or not", "", &AckermannLocalPlannerConfig::use_trans_vel_deadzone)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<bool>("use_trans_vel_deadzone", "bool", 0, "Whether to use a deadzone in the translational velocity or not", "", &AckermannLocalPlannerConfig::use_trans_vel_deadzone)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.trans_vel_deadzone = 0.01;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.trans_vel_deadzone = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.trans_vel_deadzone = 0.1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("trans_vel_deadzone", "double", 0, "Translatinal velocity minimum value", "", &AckermannLocalPlannerConfig::trans_vel_deadzone)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("trans_vel_deadzone", "double", 0, "Translatinal velocity minimum value", "", &AckermannLocalPlannerConfig::trans_vel_deadzone)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.split_ignore_length = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.split_ignore_length = 2.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.split_ignore_length = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("split_ignore_length", "double", 0, "Paths segments under this length will be ignored", "", &AckermannLocalPlannerConfig::split_ignore_length)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("split_ignore_length", "double", 0, "Paths segments under this length will be ignored", "", &AckermannLocalPlannerConfig::split_ignore_length)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.cmd_vel_avg = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.cmd_vel_avg = 20;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.cmd_vel_avg = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<int>("cmd_vel_avg", "int", 0, "Number of cmd_vel to average", "", &AckermannLocalPlannerConfig::cmd_vel_avg)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<int>("cmd_vel_avg", "int", 0, "Number of cmd_vel to average", "", &AckermannLocalPlannerConfig::cmd_vel_avg)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.odom_avg = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.odom_avg = 20;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.odom_avg = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<int>("odom_avg", "int", 0, "Number of odom to average", "", &AckermannLocalPlannerConfig::odom_avg)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<int>("odom_avg", "int", 0, "Number of odom to average", "", &AckermannLocalPlannerConfig::odom_avg)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.planner_patience = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.planner_patience = 10;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.planner_patience = 2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<int>("planner_patience", "int", 0, "number of impossible paths before replanning", "", &AckermannLocalPlannerConfig::planner_patience)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<int>("planner_patience", "int", 0, "number of impossible paths before replanning", "", &AckermannLocalPlannerConfig::planner_patience)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.hdiff_scale = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.hdiff_scale = 500.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.hdiff_scale = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("hdiff_scale", "double", 0, "The weight for the heading distance part of the cost function", "", &AckermannLocalPlannerConfig::hdiff_scale)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<double>("hdiff_scale", "double", 0, "The weight for the heading distance part of the cost function", "", &AckermannLocalPlannerConfig::hdiff_scale)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.heading_points = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.heading_points = 64;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.heading_points = 8;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<int>("heading_points", "int", 0, "The number of points to check the heading", "", &AckermannLocalPlannerConfig::heading_points)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr(new AckermannLocalPlannerConfig::ParamDescription<int>("heading_points", "int", 0, "The number of points to check the heading", "", &AckermannLocalPlannerConfig::heading_points)));
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(AckermannLocalPlannerConfig::AbstractGroupDescriptionConstPtr(new AckermannLocalPlannerConfig::GroupDescription<AckermannLocalPlannerConfig::DEFAULT, AckermannLocalPlannerConfig>(Default)));
//#line 366 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<AckermannLocalPlannerConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<AckermannLocalPlannerConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    AckermannLocalPlannerConfig __max__;
    AckermannLocalPlannerConfig __min__;
    AckermannLocalPlannerConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const AckermannLocalPlannerConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static AckermannLocalPlannerConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &AckermannLocalPlannerConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const AckermannLocalPlannerConfig &AckermannLocalPlannerConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const AckermannLocalPlannerConfig &AckermannLocalPlannerConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const AckermannLocalPlannerConfig &AckermannLocalPlannerConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<AckermannLocalPlannerConfig::AbstractParamDescriptionConstPtr> &AckermannLocalPlannerConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<AckermannLocalPlannerConfig::AbstractGroupDescriptionConstPtr> &AckermannLocalPlannerConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const AckermannLocalPlannerConfigStatics *AckermannLocalPlannerConfig::__get_statics__()
  {
    const static AckermannLocalPlannerConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = AckermannLocalPlannerConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __ACKERMANNLOCALPLANNERRECONFIGURATOR_H__
